# Generated by Django 4.1.3 on 2023-02-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('E_mail', models.EmailField(max_length=50, unique=True)),
                ('Pass1', models.CharField(max_length=20)),
                ('Pass2', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=15)),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
