# Generated by Django 4.1.3 on 2023-02-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Pass2',
        ),
    ]
